<link href="common/css/drupal/system.base.css" rel="stylesheet" type="text/css">
<link href="common/css/drupal/system.menus.css" rel="stylesheet" type="text/css">
<link href="common/css/drupal/system.messages.css" rel="stylesheet" type="text/css">
<link href="common/css/drupal/system.theme.css" rel="stylesheet" type="text/css">
<link href="common/css/drupal/inline.css" rel="stylesheet" type="text/css">
<link href="common/css/drupal/webform-layout-box.css" rel="stylesheet" type="text/css">
<link href="theme/css/styles.css" rel="stylesheet" type="text/css">
<link href="theme/css/typography.css" rel="stylesheet" type="text/css">
<style type="text/css">
  .clip-path-img-top {
    -webkit-clip-path: url(#clip-path-img-top);
    clip-path: url(#clip-path-img-top);
  }

  .clip-path-img-top-min {
    -webkit-clip-path: url(#clip-path-img-top-min);
    clip-path: url(#clip-path-img-top-min);
  }

  .clip-path-img {
    -webkit-clip-path: url(#clip-path-img);
    clip-path: url(#clip-path-img);
  }

  .clip-path-region {
    -webkit-clip-path: url(#clip-path-region);
    clip-path: url(#clip-path-region);
  }

  .clip-path-img-skew {
    -webkit-clip-path: url(#clip-path-img-skew);
    clip-path: url(#clip-path-img-skew);
  }

  .clip-path-experts {
    -webkit-clip-path: url(#clip-path-experts);
    clip-path: url(#clip-path-experts);
  }

  .clip-path-experts-a {
    -webkit-clip-path: url(#clip-path-experts-a);
    clip-path: url(#clip-path-experts-a);
  }

  .clip-path-img-top-a {
    -webkit-clip-path: url(#clip-path-img-top-a);
    clip-path: url(#clip-path-img-top-a);
  }
</style>
