<script type="text/javascript" src="theme/js/redirect.js"></script>
<!--[if (lt IE 9) & (!IEMobile)]>
<script async type="text/javascript" src="theme/js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="common/js/lib/jquery.min.js"></script>
<script type="text/javascript" src="theme/js/lib/device.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.browser.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.cookie.js"></script>

<script type="text/javascript" src="theme/js/lib/ScrollMagic.min.js"></script>
<script type="text/javascript" src="theme/js/lib/TweenMax.min.js"></script>
<script type="text/javascript" src="theme/js/lib/animation.gsap.min.js"></script>

<script type="text/javascript" src="theme/js/lib/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.mousewheel.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.simplr.smoothscroll.js"></script>
<script type="text/javascript" src="theme/js/lib/select2.full.min.js"></script>
<script type="text/javascript" src="theme/js/lib/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.maphilight.js"></script><!--only for map page-->
<script type="text/javascript" src="theme/js/lib/scrollreveal.min.js"></script>
<script type="text/javascript" src="theme/js/lib/bootstrap-modal.min.js"></script>
<script type="text/javascript" src="theme/js/lib/baguetteBox.min.js"></script><!--only for page with popup image-->
<script type="text/javascript" src="theme/js/lib/countUp.min.js"></script>
<script type="text/javascript" src="theme/js/lib/hammer.min.js"></script><!--only for page with 30years slider-->
<script type="text/javascript" src="theme/js/js.js"></script>

<script type="text/javascript" src="theme/js/lib/d3.v3.min.js"></script><!--only for weather page-->
<script type="text/javascript" src="theme/js/weather.js"></script><!--only for weather page-->

<script type="text/javascript" src="theme/js/lib/bookblock/modernizr.custom.js"></script><!--only for home page with flipbook-->
<script type="text/javascript" src="theme/js/lib/bookblock/jquerypp.custom.js"></script><!--only for home page with flipbook-->
<script type="text/javascript" src="theme/js/lib/bookblock/jquery.bookblock.js"></script><!--only for home page with flipbook-->