<script type="text/javascript" src="common/js/lib/jquery.min.js"></script>
<script type="text/javascript" src="theme/js/lib/bootstrap-modal.js"></script>
<script type="text/javascript" src="theme/js/lib/device.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.browser.js"></script>
<script type="text/javascript" src="theme/js/lib/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.maphilight.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.cookie.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.simplr.smoothscroll.js"></script>
<script type="text/javascript" src="theme/js/lib/select2.full.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="theme/js/lib/anime.min.js"></script>
<script type="text/javascript" src="theme/js/lib/main.js"></script>
<script type="text/javascript" src="theme/js/lib/ScrollMagic.min.js"></script>
<script type="text/javascript" src="theme/js/lib/TweenMax.min.js"></script>
<script type="text/javascript" src="theme/js/lib/animation.gsap.min.js"></script>

<script type="text/javascript" src="theme/js/lib/d3.v3.min.js"></script><!--only for weather page-->
<script type="text/javascript" src="theme/js/weather.js"></script><!--only for weather page-->

<script type="text/javascript" src="theme/js/js.js?t=<?php  print $timestamp?>"></script>