<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="logo">
      <a href="#">
        <img src="theme/images/logo.png" alt=""/>
      </a>
    </div>

    <div class="navigation">
      <ul class="menu">
        <li><a href="#"> TRAVEL RESOURCES </a></li>
        <li><a href="#"> PRESS</a></li>
        <li><a href="#"> CONTACT US</a></li>
        <li><a href="#"> CAREERS</a></li>
        <li><a href="#"> NEWSLETTER</a></li>
        <li><a href="#"> PARTNER LOGIN</a></li>
      </ul>
    </div>

    <div class="btn">
      <a class="link style-burgundy" href="#">SIGN UP FOR OUR NEWSLETTER</a>
    </div>

    <div class="social">
      <ul>
        <li><a class="ico ss-icon ss-social-regular ss-facebook" href="#"></a></li>
        <li><a class="ico ss-icon ss-social-regular ss-youtube" href="#"></a></li>
        <li><a class="ico ss-icon ss-social-regular ss-instagram" href="#"></a></li>
        <li><a class="ico ss-icon ss-social-regular ss-pinterest" href="#"></a></li>
      </ul>
    </div>

    <div class="img-wrap">
      <div class="img">
        <img src="theme/images/tmp/img-footer-1.png" alt=""/>
      </div>
    </div>

    <div class="copy">
      <p>&copy; 2016 Asia Transpacific Journeys</p>
    </div>

  </div>
</footer>

<a class="popup-link" href="#" data-toggle="modal" data-target="#popup-online-catalog">popup-online-catalog</a>
<div class="b-modal modal fade" id="popup-online-catalog" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close close-btn" data-dismiss="modal">+</a>
      </div>
      <div class="modal-body">
        <div class="item">
          <div class="img">
            <img src="theme/images/tmp/ViewOnlienCatalog-img-tmp-1.jpg" alt=""/>
          </div>
          <div class="text">
            <h4>WOULD YOU LIKE TO VIEW OUR online CATALOG?</h4>
            <div class="btns">
              <div class="btn">
                <a class="link style-burgundy type-read-more-a" href="#">
                  YES, Take ME TO IT
                </a>
              </div>
              <div>
                <a class="link link-close" data-dismiss="modal" href="#">No THanks</a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>