<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="left-part">
      <div class="social">
        <ul>
          <li><a class="ico ss-icon ss-social-regular ss-facebook" href="#"></a></li>
          <li><a class="ico ss-icon ss-social-regular ss-youtube" href="#"></a></li>
          <li><a class="ico ss-icon ss-social-regular ss-instagram" href="#"></a></li>
          <li><a class="ico ss-icon ss-social-regular ss-pinterest" href="#"></a></li>
        </ul>
      </div>
      <p class="copy">&copy; 2016 Asia Transpacific Journeys</p>
    </div>
    <div class="right-part">
      <div class="img"><img src="theme/images/tmp/img-footer.png" alt=""/></div>
    </div>
  </div>
  <div class="navigation">
    <ul class="menu">
      <li><a href="#"> TRAVEL RESOURCES </a></li>
      <li><a href="#"> PRESS</a></li>
      <li><a href="#"> CONTACT US</a></li>
      <li><a href="#"> CAREERS</a></li>
      <li><a href="#"> NEWSLETTER</a></li>
      <li><a href="#"> PARTNER LOGIN</a></li>
    </ul>
  </div>
<!--  height top 145, mobile 46.-->
  <svg class="clip-path" width="0" height="0">
    <defs>
      <clipPath id="clip-path-img-top">
<!--        <polygon points="0 0,0 556,646 714,1292 556,1292 0"></polygon>-->
        <polygon points="0 0,0 569,646 714,1292 569,1292 0"></polygon>
      </clipPath>
      <clipPath id="clip-path-img-top-min">
<!--        <polygon points="0 0,0 346,646 503,1292 346,1292 0"></polygon>-->
        <polygon points="0 0,0 358,646 503,1292 358,1292 0"></polygon>
      </clipPath>
      <clipPath id="clip-path-img">
        <polygon points="0 0,1292 0,1292 714,0 1000"></polygon>
      </clipPath>
      <clipPath id="clip-path-region">
        <polygon points="0 0,1292 0,1292 560,0 860"></polygon>
      </clipPath>
      <clipPath id="clip-path-img-skew">
        <polygon points="0 286,1292 0,1292 714,0 1000"></polygon>
      </clipPath>
      <clipPath id="clip-path-experts">
        <polygon points="0 0,0 766,646 621,1292 766, 1292 0"></polygon>
      </clipPath>
      <clipPath id="clip-path-img-top-a">
<!--        <polygon points="0 0,0 680,646 843,1292 680,1292 0"></polygon>-->
        <polygon points="0 0,0 698,646 843,1292 698,1292 0"></polygon>
      </clipPath>
      <clipPath id="clip-path-experts-a">
        <polygon points="0 0,0 766,646 621,1292 766, 1292 0, 646 145"></polygon>
      </clipPath>
    </defs>
  </svg>
</footer>
<div class="b-modal modal fade" id="popup-group-itenerary" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close close-btn" data-dismiss="modal">+</a>
      </div>
      <div class="modal-body">
        <div class="item">
          <div class="img">
            <img src="theme/images/tmp/modal-img-1.jpg" alt=""/>
            <a class="link type-read-more style-red" href="#">VIEW/Download <span class="ico ss-icon ss-standard ss-navigateright"></span></a>
          </div>
          <div class="text">
            <h4>VIEW YOUR GROUP TRIP ITINERARY</h4>

            <p>
              Thank you for your interest in ATJ. View and download your group trip itinerary by clicking on the link
              below.
            </p>

            <p>Personalize Tailored Journeys are our specialty. We delight in extensive, first-hand knowledge of Asia
              and
              the Pacific to craft intineraries that perfectly fit your unique travel style and preferences.</p>
          </div>
        </div>

        <div class="item">
          <div class="img">
            <img src="theme/images/tmp/modal-img-2.png" alt=""/>
            <a class="link type-read-more style-red" href="#">REQUEST CATALOG <span class="ico ss-icon ss-standard ss-navigateright"></span></a>
          </div>
          <div class="text">
            <h4>Need more information?</h4>

            <p>
              Request our Travel Catalog, where you’ll find destination information, helpful maps, insider tips and
              ideas to plan your next journey to Asia and the Pacific.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="b-modal modal fade" id="popup-tailored-planner" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close close-btn" data-dismiss="modal">+</a>
      </div>
      <div class="modal-body">
        <div class="item">
          <div class="img">
            <img src="theme/images/tmp/modal-img-3.png" alt=""/>
            <a class="link type-read-more style-red" href="#">VIEW/Download <span class="ico ss-icon ss-standard ss-navigateright"></span></a>
          </div>
          <div class="text">
            <h4>VIEW YOUR Tailored PLANNER</h4>

            <p>
              Thank you for your interest in ATJ. View and download your tailored planner by click on the link
              below.
            </p>

            <p>Personalize Tailored Journeys are our specialty. We delight in extensive, first-hand knowledge of
              Asia and the Pacific to craft intineraries that perfectly fit your unique travel style and
              preferences.</p>
          </div>
        </div>

        <div class="item">
          <div class="img">
            <img src="theme/images/tmp/modal-img-2.png" alt=""/>
            <a class="link type-read-more style-red" href="#">REQUEST CATALOG <span class="ico ss-icon ss-standard ss-navigateright"></span></a>
          </div>
          <div class="text">
            <h4>Need more information?</h4>

            <p>
              Request our Travel Catalog, where you’ll find destination information, helpful maps, insider tips
              and ideas to plan your next journey to Asia and the Pacific.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="b-modal modal fade style-wight" id="popup-terms-and-conditions" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close close-btn" data-dismiss="modal">+</a>
      </div>
      <div class="modal-body">
        <div class="logo"><img src="theme/images/tmp/tmp-logo-1.png" alt=""/></div>
        <p>TERMS AND CONDITIONS <br/>
          PAYMENT OF DEPOSIT INDICATES AGREEMENT TO THE FOLLOWING TERMS & CONDITIONS; AND AGREEMENT TO COMPLETE, SIGN AND RETURN OUR APPLICATION, WAIVER AND RELEASE OF LIABILITY, WHICH MUST BE SUBMITTED TO COMPLETE THE SIGN UP PROCESS. ALL AMOUNTS AND REFERENCES ARE MADE ON A PER PERSON BASIS.</p>
        <p>ELIGIBILITY <br/>
          You must be 18 years old (except for minors accompanied by a parent or designated responsible adult) and in acceptable health to travel on one of our tours. Acceptance of your booking is subject to our review of your application. We retain the right to request medical clearance or any other information or to refuse any applicant for any tour at any time for any reason whatsoever, at our sole discretion.</p>
        <p>INCLUSIONS/EXCLUSIONS <br/>
          Inclusions and exclusions for custom travel are detailed in your individual itinerary and for Asia Transpacific Journeys scheduled group trips in the group itinerary.</p>
        <p>
          DEPOSITS AND PAYMENTS <br/>
          For all travelers, deposits and payments (per person) are required as follows: <br/>
          At time of booking: <br/>
          • A non-refundable deposit of $1,000 per person, is due.
        </p>
        <p>At time of confirmation: <br/>
          • 50% of remaining land cost, per person, is due. <br/>
          • For all airfare booked by Asia Transpacific Journeys (including flights within Asia), 100% of airfare costs are due.</p>
        <p>
          60 days prior to departure: <br/>
          • Final payment is due. If your booking is made within 60 days of departure, the entire cost of the trip must be paid at the time of confirmation in order to secure arrangements.
        </p>
        <p>
          PAYMENT TERMS: We accept Visa, MasterCard, American Express, wire transfer or personal check. It is simplest to make credit card payments online at www.AsiaTranspacific.com/Payment. All other credit card payments require a signed credit card authorization form for each charge.
        </p>
      </div>
    </div>
  </div>
</div>