<header id="site-header" class="site-header style-a">
  <div class="container">
    <div class="info-links mobile-only">
      <a class="ico ss-icon ss-glyphish-outlined ss-phone" href="tel:"></a>
      <a class="ico ss-icon ss-glyphish-outlined ss-mail" href="mailto:"></a>
    </div>
    <div class="logo"><a href="#"><img src="theme/images/<?php isset($logo) ? print $logo : print 'logo.png'; ?>" alt=""/></a></div>
    <a class="btn-nav mobile-only" href="#"></a>
    <div class="navigation-container-mobile mobile-only">
      <div class="navigation-wrapper">
        <div class="form form-search">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="SEARCH"/>
          </div>
          <div class="form-actions">
            <input type="submit" class="form-submit"/>
          </div>
        </div>
        <div class="menu-item">
          <ul class="menu">
            <li class="expanded">
              <a href="#">Destinations</a>
              <div class="menu-inner">
                <ul class="menu">
                  <li class="active"><a href="#">Australia</a></li>
                  <li><a href="#">India</a></li>
                  <li><a href="#">New Zealand</a></li>
                  <li><a href="#">Bhutan</a></li>
                  <li><a href="#">Indonesia</a></li>
                  <li><a href="#">Papua New Guinea</a></li>
                  <li><a href="#">Borneo</a></li>
                  <li><a href="#">Japan</a></li>
                  <li><a href="#">Sri Lanka</a></li>
                  <li><a href="#">Cambodia</a></li>
                  <li><a href="#">Laos</a></li>
                  <li><a href="#">Thailand</a></li>
                  <li><a href="#">Central Asia</a></li>
                  <li><a href="#">Micronesia</a></li>
                  <li><a href="#">Tibet</a></li>
                  <li><a href="#">China</a></li>
                  <li><a href="#">Myanmar</a></li>
                  <li><a href="#">Turkey</a></li>
                  <li><a href="#">Fiji</a></li>
                  <li><a href="#">Nepal</a></li>
                  <li><a href="#">Vietnam</a></li>
                </ul>
                <div class="btns-wrap">
                  <a class="btn-map" href="#"><span>Explore Our Map</span></a>
                  <a class="btn-destination" href="#"><span>Featured Destination</span></a>
                </div>

              </div>
            </li>
            <li class="active"><a href="#">Wanderlust</a></li>
            <li><a href="#">NEWS</a></li>
            <li><a href="#">TRAVEL EXPERTS</a></li>
            <li><a href="#">ATJ DIFFERENCE</a></li>
          </ul>
        </div>
        <div class="menu-item menu-with-icons">
          <ul class="menu">
            <li class="active"><a href="#">MUST SEE (2) <span class="ico ss-icon ss-glyphish-outlined ss-pushpin"></span></a></li>
            <li class="active-trail"><a href="#">TRIP FINDER <span class="ico ss-icon ss-glyphish-outlined ss-usergroup"></span></a></li>
            <li><a href="#">MY JOURNEY <span class="ico ss-icon ss-glyphish-outlined ss-map"></span></a></li>
<!--            <li><a href="#">bOOK YOUR TRIP <span class="ico ss-icon ss-glyphish-outlined ss-tag"></span></a></li>-->
<!--            <li><a href="#">REQUEST CATALOG <span class="ico ss-icon ss-openbook ss-tag"></span></a></li>-->
            <li><a class="link style-orange type-read-more-b" href="#">BOOK YOUR TRIP</a></li>
            <li><a class="link style-purple type-read-more-b" href="#">VIEW CATALOG</a></li>
          </ul>
        </div>
        <div class="social">
          <ul>
            <li><a class="ico ss-icon ss-social-regular ss-facebook" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-twitter" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-youtube" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-instagram" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-pinterest" href="#"></a></li>
          </ul>
        </div>
        <div class="tel"><a href="tel:8006422742">800-642-2742 <span class="ico ss-icon ss-glyphish-outlined ss-phone"></span></a></div>
        <div class="mobile-logo pull-center"><img src="theme/images/logo-mobile.png" alt=""/></div>
      </div>
    </div>
    <nav class="navigation-container">
      <div class="nav-top">
        <ul class="menu">
          <li class="active"><a href="#">MUST SEE (2) <span class="ico ss-icon ss-glyphish-outlined ss-pushpin"></span></a></li>
          <li class="active-trail"><a href="#">TRIP FINDER <span class="ico ss-icon ss-glyphish-outlined ss-usergroup"></span></a></li>
          <li><a href="#">MY JOURNEY <span class="ico ss-icon ss-glyphish-outlined ss-map"></span></a></li>
        </ul>
        <div class="form form-search">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="SEARCH"/>
          </div>
          <div class="form-actions">
            <input type="submit" class="form-submit"/>
          </div>
        </div>
      </div>
      <div class="nav-bottom">
        <ul class="menu">
          <li class="expanded menu-columns">
            <a href="#">Destinations</a>
            <div class="menu-inner">
              <div class="menu-wrapper">
                <ul class="menu">
                  <li class="active"><a href="#">Australia</a></li>
                  <li><a href="#">India</a></li>
                  <li><a href="#">New Zealand</a></li>
                  <li><a href="#">Bhutan</a></li>
                  <li><a href="#">Indonesia</a></li>
                  <li><a href="#">Papua New Guinea</a></li>
                  <li><a href="#">Borneo</a></li>
                  <li><a href="#">Japan</a></li>
                  <li><a href="#">Sri Lanka</a></li>
                  <li><a href="#">Cambodia</a></li>
                  <li><a href="#">Laos</a></li>
                  <li><a href="#">Thailand</a></li>
                  <li><a href="#">Central Asia</a></li>
                  <li><a href="#">Micronesia</a></li>
                  <li><a href="#">Tibet</a></li>
                  <li><a href="#">China</a></li>
                  <li><a href="#">Myanmar</a></li>
                  <li><a href="#">Turkey</a></li>
                  <li><a href="#">Fiji</a></li>
                  <li><a href="#">Nepal</a></li>
                  <li><a href="#">Vietnam</a></li>
                </ul>
              </div>
              <div class="btns-wrap">
                <a class="btn-map" href="#"><span>Explore Our Map</span></a>
                <a class="btn-destination" href="#"><span>Featured Destination</span></a>
              </div>
            </div>
          </li>
          <li class="active"><a href="#">Wanderlust</a></li>
          <li class="expanded">
            <a href="#">ATJ DIFFERENCE</a>
            <div class="menu-inner">
              <div class="menu-wrapper">
                <ul class="menu">
                  <li><a href="#">Australia</a></li>
                  <li><a href="#">India</a></li>
                  <li><a href="#">New Zealand</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li><a href="#">NEWS</a></li>
          <li><a href="#">TRAVEL EXPERTS</a></li>
        </ul>
      </div>
    </nav>
    <div class="info-wrapper">
      <div class="info">
        <a href="tel:8006422742">800-642-2742</a>
        <div class="social">
          <ul>
            <li><a class="ico ss-icon ss-social-regular ss-facebook" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-twitter" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-youtube" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-instagram" href="#"></a></li>
            <li><a class="ico ss-icon ss-social-regular ss-pinterest" href="#"></a></li>
          </ul>
        </div>
      </div>
      <!--      <div class="btns">-->
      <!--        <div class="btn"><a href="#">bOOK YOUR TRIP <span class="ico ss-icon ss-glyphish-outlined ss-tag"></span></a></div>-->
      <!--        <div class="btn"><a href="#">REQUEST CATALOG <span class="ico ss-icon ss-openbook ss-tag"></span></a></div>-->
      <!--      </div>-->
      <div class="btns">
        <div class="btn"><a class="link style-orange type-read-more-b" href="#">BOOK YOUR TRIP</a></div>
        <div class="btn"><a class="link style-purple type-read-more-b" href="#">VIEW CATALOG</a></div>
      </div>
    </div>
    <div class="info-wrapper-tablet">
      <div class="social">
        <ul>
          <li><a class="ico ss-icon ss-social-regular ss-facebook" href="#"></a></li>
          <li><a class="ico ss-icon ss-social-regular ss-twitter" href="#"></a></li>
          <li><a class="ico ss-icon ss-social-regular ss-youtube" href="#"></a></li>
          <li><a class="ico ss-icon ss-social-regular ss-instagram" href="#"></a></li>
          <li><a class="ico ss-icon ss-social-regular ss-pinterest" href="#"></a></li>
        </ul>
      </div>
      <a class="tel-link" href="tel:8006422742">800-642-2742</a>
      <!--      <div class="btns">-->
      <!--        <div class="btn"><a href="#">REQUEST CATALOG <span class="ico ss-icon ss-openbook ss-tag"></span></a></div>-->
      <!--        <div class="btn"><a href="#">bOOK YOUR TRIP <span class="ico ss-icon ss-glyphish-outlined ss-tag"></span></a></div>-->
      <!--      </div>-->
      <div class="btns">
        <div class="btn"><a class="link style-orange type-read-more-b" href="#">BOOK YOUR TRIP</a></div>
        <div class="btn"><a class="link style-purple type-read-more-b" href="#">VIEW CATALOG</a></div>
      </div>
    </div>
  </div>
</header>